import esbuild from 'esbuild';
import process from 'process';
import builtins from 'builtin-modules';
import copy from 'esbuild-plugin-copy-watch';
import esbuildSvelte from 'esbuild-svelte';
import sveltePreprocess from 'svelte-preprocess';

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const context = await esbuild
	.context({
		banner: {
			js: banner,
		},
		entryPoints: ['src/main.ts'],
		bundle: true,
		external: [
			'obsidian',
			'electron',
			'@codemirror/autocomplete',
			'@codemirror/closebrackets',
			'@codemirror/collab',
			'@codemirror/commands',
			'@codemirror/comment',
			'@codemirror/fold',
			'@codemirror/gutter',
			'@codemirror/highlight',
			'@codemirror/history',
			'@codemirror/language',
			'@codemirror/lint',
			'@codemirror/matchbrackets',
			'@codemirror/panel',
			'@codemirror/rangeset',
			'@codemirror/rectangular-selection',
			'@codemirror/search',
			'@codemirror/state',
			'@codemirror/stream-parser',
			'@codemirror/text',
			'@codemirror/tooltip',
			'@codemirror/view',
			...builtins,
		],
		format: 'cjs',
		target: 'es2016',
		logLevel: 'info',
		sourcemap: 'inline',
		treeShaking: true,
		outdir: 'exampleVault/.obsidian/plugins/obsidian-meta-bind-plugin/',
		outbase: 'src',
		plugins: [
			copy({
				paths: [
					{
						from: './styles.css',
						to: '',
					},
					{
						from: './manifest.json',
						to: '',
					},
				],
			}),
			esbuildSvelte({
				compilerOptions: { css: true },
				preprocess: sveltePreprocess(),
			}),
		],
	})
	.catch(() => process.exit(1));

await context.watch();
