import esbuild from 'esbuild';
import process from 'process';
import builtins from 'builtin-modules';
import esbuildSvelte from 'esbuild-svelte';
import sveltePreprocess from 'svelte-preprocess';
import manifest from './manifest.json' assert { type: 'json' };

const banner = `/*
-------------------------------------------
${manifest.name} - Publish Build (based on ${manifest.version})
-------------------------------------------
By: ${manifest.author} (${manifest.authorUrl})
Time: ${new Date().toUTCString()}
Version: Publish Build (based on ${manifest.version})
-------------------------------------------
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

esbuild
	.build({
		banner: {
			js: banner,
		},
		entryPoints: ['packages/publish/src/main.ts'],
		bundle: true,
		external: [
			'obsidian',
			'electron',
			'@codemirror/autocomplete',
			'@codemirror/closebrackets',
			'@codemirror/collab',
			'@codemirror/commands',
			'@codemirror/comment',
			'@codemirror/fold',
			'@codemirror/gutter',
			'@codemirror/highlight',
			'@codemirror/history',
			'@codemirror/language',
			'@codemirror/lint',
			'@codemirror/matchbrackets',
			'@codemirror/panel',
			'@codemirror/rangeset',
			'@codemirror/rectangular-selection',
			'@codemirror/search',
			'@codemirror/state',
			'@codemirror/stream-parser',
			'@codemirror/text',
			'@codemirror/tooltip',
			'@codemirror/view',
			...builtins,
		],
		format: 'iife',
		globalName: 'meta_bind_publish',
		target: 'es2016',
		logLevel: 'info',
		sourcemap: false,
		treeShaking: true,
		minify: true,
		outfile: './Publish.js',
		define: {
			MB_GLOBAL_CONFIG_DEV_BUILD: 'false',
		},
		plugins: [
			esbuildSvelte({
				compilerOptions: { css: 'injected' },
				preprocess: sveltePreprocess(),
				filterWarnings: warning => {
					// we don't want warnings from node modules that we can do nothing about
					return !warning.filename.includes('node_modules');
				},
			}),
		],
	})
	.catch(() => process.exit(1));
